apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: simple-nodejs-app-zdh7
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: simple-nodejs-app-zdh7
    app.kubernetes.io/part-of: nodejs-users
  name: simple-nodejs-app-zdh7
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: simple-nodejs-app-zdh7
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: simple-nodejs-app-zdh7
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ctij-tenant/nodejs-users/simple-nodejs-app-zdh7@sha256:9c008b66c008e717014bdcffeb4f1de248eb06455731b21e5cdc1e591edad34c
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
